name: Run Smoke Tests

on:
  deployment:

jobs:
  smoke-test:
    name: Smoke Tests against ${{github.event.deployment.environment}}
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: contains(github.event.deployment.environment, 'Production')
    steps:
      - name: Get deployment URL
        id: deployment
        uses: dorshinar/get-deployment-url@f607ab4ab091084cc08272a71919291e71e6d800
        timeout-minutes: 5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run smoke tests
        run: npm run test:smoke
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.deployment.outputs.deployment }}
